CREATE TABLE IF NOT EXISTS public.cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  title text,
  subtitle text,
  description text,
  coverImage text,
  type text,
  category text,
  externalLink text,
  channelUrl text,
  gameLinks jsonb,
  iconImage text,
  tags jsonb,
  date text,
  badgeText text,
  isPinned bool,
  channel_url text,
  external_link text,
  video_url text,
  cover_image text,
  game_links text,
  icon_image text,
  image_index int4,
  slider_images text[]
);